# Generated by Django 5.2.12 on 2026-05-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(choices=[("general", "General"), ("practice", "Practice"), ("final", "Final")], default="general", max_length=20),
        ),
        migrations.AddField(
            model_name="quiz",
            name="topic",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quizzes", to="learn.topic"),
        ),
    ]
