PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO django_migrations VALUES(1,'contenttypes','0001_initial','2026-03-04 17:53:09.521578');
INSERT INTO django_migrations VALUES(2,'contenttypes','0002_remove_content_type_name','2026-03-04 17:53:09.528084');
INSERT INTO django_migrations VALUES(3,'auth','0001_initial','2026-03-04 17:53:09.537597');
INSERT INTO django_migrations VALUES(4,'auth','0002_alter_permission_name_max_length','2026-03-04 17:53:09.543297');
INSERT INTO django_migrations VALUES(5,'auth','0003_alter_user_email_max_length','2026-03-04 17:53:09.546298');
INSERT INTO django_migrations VALUES(6,'auth','0004_alter_user_username_opts','2026-03-04 17:53:09.551337');
INSERT INTO django_migrations VALUES(7,'auth','0005_alter_user_last_login_null','2026-03-04 17:53:09.556335');
INSERT INTO django_migrations VALUES(8,'auth','0006_require_contenttypes_0002','2026-03-04 17:53:09.558501');
INSERT INTO django_migrations VALUES(9,'auth','0007_alter_validators_add_error_messages','2026-03-04 17:53:09.562502');
INSERT INTO django_migrations VALUES(10,'auth','0008_alter_user_username_max_length','2026-03-04 17:53:09.568006');
INSERT INTO django_migrations VALUES(11,'auth','0009_alter_user_last_name_max_length','2026-03-04 17:53:09.572519');
INSERT INTO django_migrations VALUES(12,'auth','0010_alter_group_name_max_length','2026-03-04 17:53:09.577520');
INSERT INTO django_migrations VALUES(13,'auth','0011_update_proxy_permissions','2026-03-04 17:53:09.581622');
INSERT INTO django_migrations VALUES(14,'auth','0012_alter_user_first_name_max_length','2026-03-04 17:53:09.586607');
INSERT INTO django_migrations VALUES(15,'accounts','0001_initial','2026-03-04 17:53:09.596365');
INSERT INTO django_migrations VALUES(16,'admin','0001_initial','2026-03-04 17:53:09.605540');
INSERT INTO django_migrations VALUES(17,'admin','0002_logentry_remove_auto_add','2026-03-04 17:53:09.612688');
INSERT INTO django_migrations VALUES(18,'admin','0003_logentry_add_action_flag_choices','2026-03-04 17:53:09.618714');
INSERT INTO django_migrations VALUES(19,'languages','0001_initial','2026-03-04 17:53:09.623713');
INSERT INTO django_migrations VALUES(20,'quizzes','0001_initial','2026-03-04 17:53:09.641817');
INSERT INTO django_migrations VALUES(21,'ai_solutions','0001_initial','2026-03-04 17:53:09.650340');
INSERT INTO django_migrations VALUES(22,'results','0001_initial','2026-03-04 17:53:09.667390');
INSERT INTO django_migrations VALUES(23,'contests','0001_initial','2026-03-04 17:53:09.693775');
INSERT INTO django_migrations VALUES(24,'leaderboard','0001_initial','2026-03-04 17:53:09.712528');
INSERT INTO django_migrations VALUES(25,'sessions','0001_initial','2026-03-04 17:53:09.719551');
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO django_content_type VALUES(1,'admin','logentry');
INSERT INTO django_content_type VALUES(2,'auth','permission');
INSERT INTO django_content_type VALUES(3,'auth','group');
INSERT INTO django_content_type VALUES(4,'contenttypes','contenttype');
INSERT INTO django_content_type VALUES(5,'sessions','session');
INSERT INTO django_content_type VALUES(6,'accounts','customuser');
INSERT INTO django_content_type VALUES(7,'languages','language');
INSERT INTO django_content_type VALUES(8,'quizzes','question');
INSERT INTO django_content_type VALUES(9,'quizzes','option');
INSERT INTO django_content_type VALUES(10,'quizzes','quiz');
INSERT INTO django_content_type VALUES(11,'results','userresult');
INSERT INTO django_content_type VALUES(12,'results','useranswer');
INSERT INTO django_content_type VALUES(13,'leaderboard','leaderboardentry');
INSERT INTO django_content_type VALUES(14,'contests','contest');
INSERT INTO django_content_type VALUES(15,'contests','contestparticipant');
INSERT INTO django_content_type VALUES(16,'ai_solutions','aiexplanation');
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO auth_permission VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO auth_permission VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO auth_permission VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO auth_permission VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO auth_permission VALUES(5,2,'add_permission','Can add permission');
INSERT INTO auth_permission VALUES(6,2,'change_permission','Can change permission');
INSERT INTO auth_permission VALUES(7,2,'delete_permission','Can delete permission');
INSERT INTO auth_permission VALUES(8,2,'view_permission','Can view permission');
INSERT INTO auth_permission VALUES(9,3,'add_group','Can add group');
INSERT INTO auth_permission VALUES(10,3,'change_group','Can change group');
INSERT INTO auth_permission VALUES(11,3,'delete_group','Can delete group');
INSERT INTO auth_permission VALUES(12,3,'view_group','Can view group');
INSERT INTO auth_permission VALUES(13,4,'add_contenttype','Can add content type');
INSERT INTO auth_permission VALUES(14,4,'change_contenttype','Can change content type');
INSERT INTO auth_permission VALUES(15,4,'delete_contenttype','Can delete content type');
INSERT INTO auth_permission VALUES(16,4,'view_contenttype','Can view content type');
INSERT INTO auth_permission VALUES(17,5,'add_session','Can add session');
INSERT INTO auth_permission VALUES(18,5,'change_session','Can change session');
INSERT INTO auth_permission VALUES(19,5,'delete_session','Can delete session');
INSERT INTO auth_permission VALUES(20,5,'view_session','Can view session');
INSERT INTO auth_permission VALUES(21,6,'add_customuser','Can add User');
INSERT INTO auth_permission VALUES(22,6,'change_customuser','Can change User');
INSERT INTO auth_permission VALUES(23,6,'delete_customuser','Can delete User');
INSERT INTO auth_permission VALUES(24,6,'view_customuser','Can view User');
INSERT INTO auth_permission VALUES(25,7,'add_language','Can add Language');
INSERT INTO auth_permission VALUES(26,7,'change_language','Can change Language');
INSERT INTO auth_permission VALUES(27,7,'delete_language','Can delete Language');
INSERT INTO auth_permission VALUES(28,7,'view_language','Can view Language');
INSERT INTO auth_permission VALUES(29,8,'add_question','Can add Question');
INSERT INTO auth_permission VALUES(30,8,'change_question','Can change Question');
INSERT INTO auth_permission VALUES(31,8,'delete_question','Can delete Question');
INSERT INTO auth_permission VALUES(32,8,'view_question','Can view Question');
INSERT INTO auth_permission VALUES(33,9,'add_option','Can add Option');
INSERT INTO auth_permission VALUES(34,9,'change_option','Can change Option');
INSERT INTO auth_permission VALUES(35,9,'delete_option','Can delete Option');
INSERT INTO auth_permission VALUES(36,9,'view_option','Can view Option');
INSERT INTO auth_permission VALUES(37,10,'add_quiz','Can add Quiz');
INSERT INTO auth_permission VALUES(38,10,'change_quiz','Can change Quiz');
INSERT INTO auth_permission VALUES(39,10,'delete_quiz','Can delete Quiz');
INSERT INTO auth_permission VALUES(40,10,'view_quiz','Can view Quiz');
INSERT INTO auth_permission VALUES(41,11,'add_userresult','Can add User Result');
INSERT INTO auth_permission VALUES(42,11,'change_userresult','Can change User Result');
INSERT INTO auth_permission VALUES(43,11,'delete_userresult','Can delete User Result');
INSERT INTO auth_permission VALUES(44,11,'view_userresult','Can view User Result');
INSERT INTO auth_permission VALUES(45,12,'add_useranswer','Can add User Answer');
INSERT INTO auth_permission VALUES(46,12,'change_useranswer','Can change User Answer');
INSERT INTO auth_permission VALUES(47,12,'delete_useranswer','Can delete User Answer');
INSERT INTO auth_permission VALUES(48,12,'view_useranswer','Can view User Answer');
INSERT INTO auth_permission VALUES(49,13,'add_leaderboardentry','Can add Leaderboard Entry');
INSERT INTO auth_permission VALUES(50,13,'change_leaderboardentry','Can change Leaderboard Entry');
INSERT INTO auth_permission VALUES(51,13,'delete_leaderboardentry','Can delete Leaderboard Entry');
INSERT INTO auth_permission VALUES(52,13,'view_leaderboardentry','Can view Leaderboard Entry');
INSERT INTO auth_permission VALUES(53,14,'add_contest','Can add Contest');
INSERT INTO auth_permission VALUES(54,14,'change_contest','Can change Contest');
INSERT INTO auth_permission VALUES(55,14,'delete_contest','Can delete Contest');
INSERT INTO auth_permission VALUES(56,14,'view_contest','Can view Contest');
INSERT INTO auth_permission VALUES(57,15,'add_contestparticipant','Can add Contest Participant');
INSERT INTO auth_permission VALUES(58,15,'change_contestparticipant','Can change Contest Participant');
INSERT INTO auth_permission VALUES(59,15,'delete_contestparticipant','Can delete Contest Participant');
INSERT INTO auth_permission VALUES(60,15,'view_contestparticipant','Can view Contest Participant');
INSERT INTO auth_permission VALUES(61,16,'add_aiexplanation','Can add AI Explanation');
INSERT INTO auth_permission VALUES(62,16,'change_aiexplanation','Can change AI Explanation');
INSERT INTO auth_permission VALUES(63,16,'delete_aiexplanation','Can delete AI Explanation');
INSERT INTO auth_permission VALUES(64,16,'view_aiexplanation','Can view AI Explanation');
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "accounts_customuser" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "avatar" varchar(100) NULL, "bio" text NOT NULL, "total_score" integer unsigned NOT NULL CHECK ("total_score" >= 0), "quizzes_taken" integer unsigned NOT NULL CHECK ("quizzes_taken" >= 0), "best_streak" integer unsigned NOT NULL CHECK ("best_streak" >= 0));
INSERT INTO accounts_customuser VALUES(2,'pbkdf2_sha256$1000000$boHScw0o6IrPgawuEORUSs$MHuMiQFdOh2DtY0zdYeM7uaC75wKkB7GT6OHTSyWb+4=','2026-03-04 18:32:31.539942',1,'admin','','',1,1,'2026-03-04 18:30:22.751683','admin@devquiz.com','','',0,0,0);
CREATE TABLE IF NOT EXISTS "accounts_customuser_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "accounts_customuser_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "languages_language" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "is_published" bool NOT NULL, "published_at" datetime NULL, "name" varchar(100) NOT NULL UNIQUE, "slug" varchar(120) NOT NULL UNIQUE, "icon" varchar(100) NULL, "icon_svg" text NOT NULL, "description" text NOT NULL, "sort_order" smallint unsigned NOT NULL CHECK ("sort_order" >= 0));
CREATE TABLE IF NOT EXISTS "quizzes_option" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" varchar(500) NOT NULL, "is_correct" bool NOT NULL, "order" smallint unsigned NOT NULL CHECK ("order" >= 0), "question_id" bigint NOT NULL REFERENCES "quizzes_question" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "quizzes_quiz" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "is_published" bool NOT NULL, "published_at" datetime NULL, "title" varchar(200) NOT NULL, "slug" varchar(220) NOT NULL UNIQUE, "difficulty" varchar(20) NOT NULL, "description" text NOT NULL, "time_limit" integer unsigned NULL CHECK ("time_limit" >= 0), "created_by_id" bigint NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "language_id" bigint NOT NULL REFERENCES "languages_language" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "quizzes_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" text NOT NULL, "explanation" text NOT NULL, "order" smallint unsigned NOT NULL CHECK ("order" >= 0), "points" smallint unsigned NOT NULL CHECK ("points" >= 0), "question_type" varchar(20) NOT NULL, "quiz_id" bigint NOT NULL REFERENCES "quizzes_quiz" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "ai_solutions_aiexplanation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "content" text NOT NULL, "model_used" varchar(100) NOT NULL, "prompt_tokens" integer unsigned NOT NULL CHECK ("prompt_tokens" >= 0), "completion_tokens" integer unsigned NOT NULL CHECK ("completion_tokens" >= 0), "is_approved" bool NOT NULL, "question_id" bigint NOT NULL UNIQUE REFERENCES "quizzes_question" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "results_userresult" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "score" integer unsigned NOT NULL CHECK ("score" >= 0), "total_points" integer unsigned NOT NULL CHECK ("total_points" >= 0), "started_at" datetime NOT NULL, "completed_at" datetime NULL, "is_completed" bool NOT NULL, "quiz_id" bigint NOT NULL REFERENCES "quizzes_quiz" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "results_useranswer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "answered_at" datetime NOT NULL, "question_id" bigint NOT NULL REFERENCES "quizzes_question" ("id") DEFERRABLE INITIALLY DEFERRED, "selected_option_id" bigint NULL REFERENCES "quizzes_option" ("id") DEFERRABLE INITIALLY DEFERRED, "result_id" bigint NOT NULL REFERENCES "results_userresult" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "contests_contest" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "is_published" bool NOT NULL, "published_at" datetime NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "start_time" datetime NOT NULL, "end_time" datetime NOT NULL, "max_participants" integer unsigned NULL CHECK ("max_participants" >= 0), "is_active" bool NOT NULL, "created_by_id" bigint NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "quiz_id" bigint NOT NULL REFERENCES "quizzes_quiz" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "contests_contestparticipant" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "joined_at" datetime NOT NULL, "final_rank" integer unsigned NULL CHECK ("final_rank" >= 0), "contest_id" bigint NOT NULL REFERENCES "contests_contest" ("id") DEFERRABLE INITIALLY DEFERRED, "result_id" bigint NULL UNIQUE REFERENCES "results_userresult" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "leaderboard_leaderboardentry" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "total_score" integer unsigned NOT NULL CHECK ("total_score" >= 0), "quizzes_completed" integer unsigned NOT NULL CHECK ("quizzes_completed" >= 0), "rank" integer unsigned NOT NULL CHECK ("rank" >= 0), "language_id" bigint NULL REFERENCES "languages_language" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
INSERT INTO django_session VALUES('pvbbk7w6o1bawkk9tjuugn2l7wejcrqc','.eJxVjMEOwiAQRP-FsyGbAnXx6N1vIMsuSNVAUtqT8d9tkx50jvPezFsFWpcS1p7mMIm6qEGdfrtI_Ex1B_Kgem-aW13mKepd0Qft-tYkva6H-3dQqJdt7S3FlMHlKCOPgAwsnjNhjB6zOxMaMS4DD8biFgsWsichi4zJgfp8AQ1lOHU:1vxr1L:HH8L_wid2lQeH0cwAlPvkdROrzZ1yqxZZd2d3lPYa5Q','2026-03-18 18:32:31.541400');
PRAGMA writable_schema=ON;
CREATE TABLE IF NOT EXISTS sqlite_sequence(name,seq);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('django_migrations',25);
INSERT INTO sqlite_sequence VALUES('django_content_type',16);
INSERT INTO sqlite_sequence VALUES('auth_permission',64);
INSERT INTO sqlite_sequence VALUES('auth_group',0);
INSERT INTO sqlite_sequence VALUES('django_admin_log',0);
INSERT INTO sqlite_sequence VALUES('quizzes_question',0);
INSERT INTO sqlite_sequence VALUES('accounts_customuser',2);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq" ON "accounts_customuser_groups" ("customuser_id", "group_id");
CREATE INDEX "accounts_customuser_groups_customuser_id_bc55088e" ON "accounts_customuser_groups" ("customuser_id");
CREATE INDEX "accounts_customuser_groups_group_id_86ba5f9e" ON "accounts_customuser_groups" ("group_id");
CREATE UNIQUE INDEX "accounts_customuser_user_permissions_customuser_id_permission_id_9632a709_uniq" ON "accounts_customuser_user_permissions" ("customuser_id", "permission_id");
CREATE INDEX "accounts_customuser_user_permissions_customuser_id_0deaefae" ON "accounts_customuser_user_permissions" ("customuser_id");
CREATE INDEX "accounts_customuser_user_permissions_permission_id_aea3d0e5" ON "accounts_customuser_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "quizzes_option_question_id_6a357926" ON "quizzes_option" ("question_id");
CREATE INDEX "quizzes_quiz_created_by_id_25f906f5" ON "quizzes_quiz" ("created_by_id");
CREATE INDEX "quizzes_quiz_language_id_90c318b2" ON "quizzes_quiz" ("language_id");
CREATE INDEX "quizzes_question_quiz_id_70961654" ON "quizzes_question" ("quiz_id");
CREATE INDEX "results_userresult_quiz_id_4a83879d" ON "results_userresult" ("quiz_id");
CREATE INDEX "results_userresult_user_id_52147c79" ON "results_userresult" ("user_id");
CREATE UNIQUE INDEX "results_useranswer_result_id_question_id_91109c62_uniq" ON "results_useranswer" ("result_id", "question_id");
CREATE INDEX "results_useranswer_question_id_bdb2ea54" ON "results_useranswer" ("question_id");
CREATE INDEX "results_useranswer_selected_option_id_2e51a9eb" ON "results_useranswer" ("selected_option_id");
CREATE INDEX "results_useranswer_result_id_fada4d7e" ON "results_useranswer" ("result_id");
CREATE INDEX "contests_contest_created_by_id_85dab57f" ON "contests_contest" ("created_by_id");
CREATE INDEX "contests_contest_quiz_id_a045c479" ON "contests_contest" ("quiz_id");
CREATE UNIQUE INDEX "contests_contestparticipant_contest_id_user_id_2166a7f6_uniq" ON "contests_contestparticipant" ("contest_id", "user_id");
CREATE INDEX "contests_contestparticipant_contest_id_e48e622f" ON "contests_contestparticipant" ("contest_id");
CREATE INDEX "contests_contestparticipant_user_id_14e11936" ON "contests_contestparticipant" ("user_id");
CREATE UNIQUE INDEX "leaderboard_leaderboardentry_user_id_language_id_8c3fd96f_uniq" ON "leaderboard_leaderboardentry" ("user_id", "language_id");
CREATE INDEX "leaderboard_leaderboardentry_language_id_3a685e7e" ON "leaderboard_leaderboardentry" ("language_id");
CREATE INDEX "leaderboard_leaderboardentry_user_id_2a062760" ON "leaderboard_leaderboardentry" ("user_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
PRAGMA writable_schema=OFF;
COMMIT;
