# Generated by Django 5.2.12 on 2026-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="category",
            field=models.CharField(choices=[("general", "General"), ("final", "Final")], default="general", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboardentry",
            unique_together={("user", "language", "category")},
        ),
    ]
