# Generated by Django 5.2.12 on 2026-05-04 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
        ("results", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True, help_text="Lesson content. Supports markdown-style headings.")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("language", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="topics", to="languages.language")),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["language", "sort_order", "title"],
                "unique_together": {("language", "slug")},
            },
        ),
        migrations.CreateModel(
            name="TopicProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="topic_progress", to="results.userresult")),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progress", to="learn.topic")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="topic_progress", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Topic Progress",
                "verbose_name_plural": "Topic Progress",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "topic")},
            },
        ),
    ]
