# Generated by Django 5.2.12 on 2026-05-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, help_text="Short overview shown in the resource list.")),
                ("content", models.TextField(help_text="Markdown content. Use triple backticks for code blocks.")),
                ("resource_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resources", to="learn.topic"),
                ),
            ],
            options={
                "verbose_name": "Topic Resource",
                "verbose_name_plural": "Topic Resources",
                "ordering": ["topic", "sort_order", "title"],
            },
        ),
    ]
